CREATE TABLE IF NOT EXISTS lyrics (
  `uid` VARCHAR(32) NOT NULL,
  `slug` VARCHAR(256) NOT NULL,
  `artist` VARCHAR(256),
  `song` VARCHAR(256), 
  `content` MEDIUMTEXT,
  `source` VARCHAR(256),
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;